// assets.js — auto-generated index of public/assets
// Paths are web-root-relative (served from /public). Use directly as src.
// Regenerate after adding assets. Total files indexed: 894

const ASSET_BASE = '/assets';

// SOUNDS (100 files)
export const sounds = {
  "back_001": "/assets/kenney_interface-sounds/Audio/back_001.ogg",
  "back_002": "/assets/kenney_interface-sounds/Audio/back_002.ogg",
  "back_003": "/assets/kenney_interface-sounds/Audio/back_003.ogg",
  "back_004": "/assets/kenney_interface-sounds/Audio/back_004.ogg",
  "bong_001": "/assets/kenney_interface-sounds/Audio/bong_001.ogg",
  "click_001": "/assets/kenney_interface-sounds/Audio/click_001.ogg",
  "click_002": "/assets/kenney_interface-sounds/Audio/click_002.ogg",
  "click_003": "/assets/kenney_interface-sounds/Audio/click_003.ogg",
  "click_004": "/assets/kenney_interface-sounds/Audio/click_004.ogg",
  "click_005": "/assets/kenney_interface-sounds/Audio/click_005.ogg",
  "close_001": "/assets/kenney_interface-sounds/Audio/close_001.ogg",
  "close_002": "/assets/kenney_interface-sounds/Audio/close_002.ogg",
  "close_003": "/assets/kenney_interface-sounds/Audio/close_003.ogg",
  "close_004": "/assets/kenney_interface-sounds/Audio/close_004.ogg",
  "confirmation_001": "/assets/kenney_interface-sounds/Audio/confirmation_001.ogg",
  "confirmation_002": "/assets/kenney_interface-sounds/Audio/confirmation_002.ogg",
  "confirmation_003": "/assets/kenney_interface-sounds/Audio/confirmation_003.ogg",
  "confirmation_004": "/assets/kenney_interface-sounds/Audio/confirmation_004.ogg",
  "drop_001": "/assets/kenney_interface-sounds/Audio/drop_001.ogg",
  "drop_002": "/assets/kenney_interface-sounds/Audio/drop_002.ogg",
  "drop_003": "/assets/kenney_interface-sounds/Audio/drop_003.ogg",
  "drop_004": "/assets/kenney_interface-sounds/Audio/drop_004.ogg",
  "error_001": "/assets/kenney_interface-sounds/Audio/error_001.ogg",
  "error_002": "/assets/kenney_interface-sounds/Audio/error_002.ogg",
  "error_003": "/assets/kenney_interface-sounds/Audio/error_003.ogg",
  "error_004": "/assets/kenney_interface-sounds/Audio/error_004.ogg",
  "error_005": "/assets/kenney_interface-sounds/Audio/error_005.ogg",
  "error_006": "/assets/kenney_interface-sounds/Audio/error_006.ogg",
  "error_007": "/assets/kenney_interface-sounds/Audio/error_007.ogg",
  "error_008": "/assets/kenney_interface-sounds/Audio/error_008.ogg",
  "glass_001": "/assets/kenney_interface-sounds/Audio/glass_001.ogg",
  "glass_002": "/assets/kenney_interface-sounds/Audio/glass_002.ogg",
  "glass_003": "/assets/kenney_interface-sounds/Audio/glass_003.ogg",
  "glass_004": "/assets/kenney_interface-sounds/Audio/glass_004.ogg",
  "glass_005": "/assets/kenney_interface-sounds/Audio/glass_005.ogg",
  "glass_006": "/assets/kenney_interface-sounds/Audio/glass_006.ogg",
  "glitch_001": "/assets/kenney_interface-sounds/Audio/glitch_001.ogg",
  "glitch_002": "/assets/kenney_interface-sounds/Audio/glitch_002.ogg",
  "glitch_003": "/assets/kenney_interface-sounds/Audio/glitch_003.ogg",
  "glitch_004": "/assets/kenney_interface-sounds/Audio/glitch_004.ogg",
  "maximize_001": "/assets/kenney_interface-sounds/Audio/maximize_001.ogg",
  "maximize_002": "/assets/kenney_interface-sounds/Audio/maximize_002.ogg",
  "maximize_003": "/assets/kenney_interface-sounds/Audio/maximize_003.ogg",
  "maximize_004": "/assets/kenney_interface-sounds/Audio/maximize_004.ogg",
  "maximize_005": "/assets/kenney_interface-sounds/Audio/maximize_005.ogg",
  "maximize_006": "/assets/kenney_interface-sounds/Audio/maximize_006.ogg",
  "maximize_007": "/assets/kenney_interface-sounds/Audio/maximize_007.ogg",
  "maximize_008": "/assets/kenney_interface-sounds/Audio/maximize_008.ogg",
  "maximize_009": "/assets/kenney_interface-sounds/Audio/maximize_009.ogg",
  "minimize_001": "/assets/kenney_interface-sounds/Audio/minimize_001.ogg",
  "minimize_002": "/assets/kenney_interface-sounds/Audio/minimize_002.ogg",
  "minimize_003": "/assets/kenney_interface-sounds/Audio/minimize_003.ogg",
  "minimize_004": "/assets/kenney_interface-sounds/Audio/minimize_004.ogg",
  "minimize_005": "/assets/kenney_interface-sounds/Audio/minimize_005.ogg",
  "minimize_006": "/assets/kenney_interface-sounds/Audio/minimize_006.ogg",
  "minimize_007": "/assets/kenney_interface-sounds/Audio/minimize_007.ogg",
  "minimize_008": "/assets/kenney_interface-sounds/Audio/minimize_008.ogg",
  "minimize_009": "/assets/kenney_interface-sounds/Audio/minimize_009.ogg",
  "open_001": "/assets/kenney_interface-sounds/Audio/open_001.ogg",
  "open_002": "/assets/kenney_interface-sounds/Audio/open_002.ogg",
  "open_003": "/assets/kenney_interface-sounds/Audio/open_003.ogg",
  "open_004": "/assets/kenney_interface-sounds/Audio/open_004.ogg",
  "pluck_001": "/assets/kenney_interface-sounds/Audio/pluck_001.ogg",
  "pluck_002": "/assets/kenney_interface-sounds/Audio/pluck_002.ogg",
  "question_001": "/assets/kenney_interface-sounds/Audio/question_001.ogg",
  "question_002": "/assets/kenney_interface-sounds/Audio/question_002.ogg",
  "question_003": "/assets/kenney_interface-sounds/Audio/question_003.ogg",
  "question_004": "/assets/kenney_interface-sounds/Audio/question_004.ogg",
  "scratch_001": "/assets/kenney_interface-sounds/Audio/scratch_001.ogg",
  "scratch_002": "/assets/kenney_interface-sounds/Audio/scratch_002.ogg",
  "scratch_003": "/assets/kenney_interface-sounds/Audio/scratch_003.ogg",
  "scratch_004": "/assets/kenney_interface-sounds/Audio/scratch_004.ogg",
  "scratch_005": "/assets/kenney_interface-sounds/Audio/scratch_005.ogg",
  "scroll_001": "/assets/kenney_interface-sounds/Audio/scroll_001.ogg",
  "scroll_002": "/assets/kenney_interface-sounds/Audio/scroll_002.ogg",
  "scroll_003": "/assets/kenney_interface-sounds/Audio/scroll_003.ogg",
  "scroll_004": "/assets/kenney_interface-sounds/Audio/scroll_004.ogg",
  "scroll_005": "/assets/kenney_interface-sounds/Audio/scroll_005.ogg",
  "select_001": "/assets/kenney_interface-sounds/Audio/select_001.ogg",
  "select_002": "/assets/kenney_interface-sounds/Audio/select_002.ogg",
  "select_003": "/assets/kenney_interface-sounds/Audio/select_003.ogg",
  "select_004": "/assets/kenney_interface-sounds/Audio/select_004.ogg",
  "select_005": "/assets/kenney_interface-sounds/Audio/select_005.ogg",
  "select_006": "/assets/kenney_interface-sounds/Audio/select_006.ogg",
  "select_007": "/assets/kenney_interface-sounds/Audio/select_007.ogg",
  "select_008": "/assets/kenney_interface-sounds/Audio/select_008.ogg",
  "switch_001": "/assets/kenney_interface-sounds/Audio/switch_001.ogg",
  "switch_002": "/assets/kenney_interface-sounds/Audio/switch_002.ogg",
  "switch_003": "/assets/kenney_interface-sounds/Audio/switch_003.ogg",
  "switch_004": "/assets/kenney_interface-sounds/Audio/switch_004.ogg",
  "switch_005": "/assets/kenney_interface-sounds/Audio/switch_005.ogg",
  "switch_006": "/assets/kenney_interface-sounds/Audio/switch_006.ogg",
  "switch_007": "/assets/kenney_interface-sounds/Audio/switch_007.ogg",
  "tick_001": "/assets/kenney_interface-sounds/Audio/tick_001.ogg",
  "tick_002": "/assets/kenney_interface-sounds/Audio/tick_002.ogg",
  "tick_004": "/assets/kenney_interface-sounds/Audio/tick_004.ogg",
  "toggle_001": "/assets/kenney_interface-sounds/Audio/toggle_001.ogg",
  "toggle_002": "/assets/kenney_interface-sounds/Audio/toggle_002.ogg",
  "toggle_003": "/assets/kenney_interface-sounds/Audio/toggle_003.ogg",
  "toggle_004": "/assets/kenney_interface-sounds/Audio/toggle_004.ogg",
};

// CARDS_LARGE (56 files)
export const cardsLarge = {
  "card_back": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_back.png",
  "card_clubs_02": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_02.png",
  "card_clubs_03": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_03.png",
  "card_clubs_04": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_04.png",
  "card_clubs_05": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_05.png",
  "card_clubs_06": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_06.png",
  "card_clubs_07": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_07.png",
  "card_clubs_08": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_08.png",
  "card_clubs_09": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_09.png",
  "card_clubs_10": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_10.png",
  "card_clubs_A": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_A.png",
  "card_clubs_J": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_J.png",
  "card_clubs_K": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_K.png",
  "card_clubs_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_clubs_Q.png",
  "card_diamonds_02": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_02.png",
  "card_diamonds_03": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_03.png",
  "card_diamonds_04": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_04.png",
  "card_diamonds_05": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_05.png",
  "card_diamonds_06": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_06.png",
  "card_diamonds_07": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_07.png",
  "card_diamonds_08": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_08.png",
  "card_diamonds_09": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_09.png",
  "card_diamonds_10": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_10.png",
  "card_diamonds_A": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_A.png",
  "card_diamonds_J": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_J.png",
  "card_diamonds_K": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_K.png",
  "card_diamonds_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_diamonds_Q.png",
  "card_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_empty.png",
  "card_hearts_02": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_02.png",
  "card_hearts_03": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_03.png",
  "card_hearts_04": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_04.png",
  "card_hearts_05": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_05.png",
  "card_hearts_06": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_06.png",
  "card_hearts_07": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_07.png",
  "card_hearts_08": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_08.png",
  "card_hearts_09": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_09.png",
  "card_hearts_10": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_10.png",
  "card_hearts_A": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_A.png",
  "card_hearts_J": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_J.png",
  "card_hearts_K": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_K.png",
  "card_hearts_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_hearts_Q.png",
  "card_joker_black": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_joker_black.png",
  "card_joker_red": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_joker_red.png",
  "card_spades_02": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_02.png",
  "card_spades_03": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_03.png",
  "card_spades_04": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_04.png",
  "card_spades_05": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_05.png",
  "card_spades_06": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_06.png",
  "card_spades_07": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_07.png",
  "card_spades_08": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_08.png",
  "card_spades_09": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_09.png",
  "card_spades_10": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_10.png",
  "card_spades_A": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_A.png",
  "card_spades_J": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_J.png",
  "card_spades_K": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_K.png",
  "card_spades_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (large)/card_spades_Q.png",
};

// CARDS_MEDIUM (136 files)
export const cardsMedium = {
  "card_back": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_back.png",
  "card_clubs_02": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_02.png",
  "card_clubs_03": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_03.png",
  "card_clubs_04": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_04.png",
  "card_clubs_05": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_05.png",
  "card_clubs_06": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_06.png",
  "card_clubs_07": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_07.png",
  "card_clubs_08": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_08.png",
  "card_clubs_09": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_09.png",
  "card_clubs_10": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_10.png",
  "card_clubs_A": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_A.png",
  "card_clubs_J": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_J.png",
  "card_clubs_K": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_K.png",
  "card_clubs_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_Q.png",
  "card_clubs_suit": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_clubs_suit.png",
  "card_diamonds_02": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_02.png",
  "card_diamonds_03": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_03.png",
  "card_diamonds_04": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_04.png",
  "card_diamonds_05": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_05.png",
  "card_diamonds_06": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_06.png",
  "card_diamonds_07": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_07.png",
  "card_diamonds_08": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_08.png",
  "card_diamonds_09": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_09.png",
  "card_diamonds_10": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_10.png",
  "card_diamonds_A": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_A.png",
  "card_diamonds_J": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_J.png",
  "card_diamonds_K": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_K.png",
  "card_diamonds_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_Q.png",
  "card_diamonds_suit": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_diamonds_suit.png",
  "card_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_empty.png",
  "card_hearts_02": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_02.png",
  "card_hearts_03": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_03.png",
  "card_hearts_04": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_04.png",
  "card_hearts_05": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_05.png",
  "card_hearts_06": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_06.png",
  "card_hearts_07": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_07.png",
  "card_hearts_08": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_08.png",
  "card_hearts_09": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_09.png",
  "card_hearts_10": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_10.png",
  "card_hearts_A": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_A.png",
  "card_hearts_J": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_J.png",
  "card_hearts_K": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_K.png",
  "card_hearts_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_Q.png",
  "card_hearts_suit": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_hearts_suit.png",
  "card_joker_black": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_joker_black.png",
  "card_joker_red": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_joker_red.png",
  "card_spades_02": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_02.png",
  "card_spades_03": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_03.png",
  "card_spades_04": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_04.png",
  "card_spades_05": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_05.png",
  "card_spades_06": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_06.png",
  "card_spades_07": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_07.png",
  "card_spades_08": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_08.png",
  "card_spades_09": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_09.png",
  "card_spades_10": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_10.png",
  "card_spades_A": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_A.png",
  "card_spades_J": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_J.png",
  "card_spades_K": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_K.png",
  "card_spades_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_Q.png",
  "card_spades_suit": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/card_spades_suit.png",
  "color_back": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_back.png",
  "color_draw": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_draw.png",
  "color_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_empty.png",
  "color_green_0": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_0.png",
  "color_green_1": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_1.png",
  "color_green_2": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_2.png",
  "color_green_3": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_3.png",
  "color_green_4": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_4.png",
  "color_green_5": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_5.png",
  "color_green_6": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_6.png",
  "color_green_7": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_7.png",
  "color_green_8": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_8.png",
  "color_green_9": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_9.png",
  "color_green_draw": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_draw.png",
  "color_green_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_empty.png",
  "color_green_reverse": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_reverse.png",
  "color_green_skip": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_green_skip.png",
  "color_purple_0": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_0.png",
  "color_purple_1": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_1.png",
  "color_purple_2": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_2.png",
  "color_purple_3": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_3.png",
  "color_purple_4": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_4.png",
  "color_purple_5": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_5.png",
  "color_purple_6": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_6.png",
  "color_purple_7": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_7.png",
  "color_purple_8": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_8.png",
  "color_purple_9": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_9.png",
  "color_purple_draw": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_draw.png",
  "color_purple_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_empty.png",
  "color_purple_reverse": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_reverse.png",
  "color_purple_skip": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_purple_skip.png",
  "color_red_0": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_0.png",
  "color_red_1": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_1.png",
  "color_red_2": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_2.png",
  "color_red_3": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_3.png",
  "color_red_4": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_4.png",
  "color_red_5": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_5.png",
  "color_red_6": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_6.png",
  "color_red_7": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_7.png",
  "color_red_8": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_8.png",
  "color_red_9": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_9.png",
  "color_red_draw": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_draw.png",
  "color_red_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_empty.png",
  "color_red_reverse": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_reverse.png",
  "color_red_skip": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_red_skip.png",
  "color_wild": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_wild.png",
  "color_yellow_0": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_0.png",
  "color_yellow_1": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_1.png",
  "color_yellow_2": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_2.png",
  "color_yellow_3": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_3.png",
  "color_yellow_4": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_4.png",
  "color_yellow_5": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_5.png",
  "color_yellow_6": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_6.png",
  "color_yellow_7": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_7.png",
  "color_yellow_8": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_8.png",
  "color_yellow_9": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_9.png",
  "color_yellow_draw": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_draw.png",
  "color_yellow_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_empty.png",
  "color_yellow_reverse": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_reverse.png",
  "color_yellow_skip": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/color_yellow_skip.png",
  "dice_1": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_1.png",
  "dice_2": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_2.png",
  "dice_3": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_3.png",
  "dice_4": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_4.png",
  "dice_5": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_5.png",
  "dice_6": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_6.png",
  "dice_decorated_1": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_decorated_1.png",
  "dice_decorated_2": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_decorated_2.png",
  "dice_decorated_3": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_decorated_3.png",
  "dice_decorated_4": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_decorated_4.png",
  "dice_decorated_5": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_decorated_5.png",
  "dice_decorated_6": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_decorated_6.png",
  "dice_decorated_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_decorated_empty.png",
  "dice_decorated_question": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_decorated_question.png",
  "dice_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_empty.png",
  "dice_question": "/assets/kenney_playing-cards-pack/PNG/Cards (medium)/dice_question.png",
};

// CARDS_SMALL (84 files)
export const cardsSmall = {
  "card_clubs_02": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_02.png",
  "card_clubs_03": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_03.png",
  "card_clubs_04": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_04.png",
  "card_clubs_05": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_05.png",
  "card_clubs_06": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_06.png",
  "card_clubs_07": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_07.png",
  "card_clubs_08": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_08.png",
  "card_clubs_09": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_09.png",
  "card_clubs_10": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_10.png",
  "card_clubs_A": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_A.png",
  "card_clubs_J": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_J.png",
  "card_clubs_K": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_K.png",
  "card_clubs_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_Q.png",
  "card_clubs_suit": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_clubs_suit.png",
  "card_diamonds_02": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_02.png",
  "card_diamonds_03": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_03.png",
  "card_diamonds_04": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_04.png",
  "card_diamonds_05": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_05.png",
  "card_diamonds_06": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_06.png",
  "card_diamonds_07": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_07.png",
  "card_diamonds_08": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_08.png",
  "card_diamonds_09": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_09.png",
  "card_diamonds_10": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_10.png",
  "card_diamonds_A": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_A.png",
  "card_diamonds_J": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_J.png",
  "card_diamonds_K": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_K.png",
  "card_diamonds_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_Q.png",
  "card_diamonds_suit": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_diamonds_suit.png",
  "card_hearts_02": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_02.png",
  "card_hearts_03": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_03.png",
  "card_hearts_04": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_04.png",
  "card_hearts_05": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_05.png",
  "card_hearts_06": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_06.png",
  "card_hearts_07": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_07.png",
  "card_hearts_08": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_08.png",
  "card_hearts_09": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_09.png",
  "card_hearts_10": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_10.png",
  "card_hearts_A": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_A.png",
  "card_hearts_J": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_J.png",
  "card_hearts_K": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_K.png",
  "card_hearts_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_Q.png",
  "card_hearts_suit": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_hearts_suit.png",
  "card_spades_02": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_02.png",
  "card_spades_03": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_03.png",
  "card_spades_04": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_04.png",
  "card_spades_05": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_05.png",
  "card_spades_06": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_06.png",
  "card_spades_07": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_07.png",
  "card_spades_08": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_08.png",
  "card_spades_09": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_09.png",
  "card_spades_10": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_10.png",
  "card_spades_A": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_A.png",
  "card_spades_J": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_J.png",
  "card_spades_K": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_K.png",
  "card_spades_Q": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_Q.png",
  "card_spades_suit": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/card_spades_suit.png",
  "dice_1": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_1.png",
  "dice_2": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_2.png",
  "dice_3": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_3.png",
  "dice_4": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_4.png",
  "dice_5": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_5.png",
  "dice_6": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_6.png",
  "dice_decorated_1": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_decorated_1.png",
  "dice_decorated_2": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_decorated_2.png",
  "dice_decorated_3": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_decorated_3.png",
  "dice_decorated_4": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_decorated_4.png",
  "dice_decorated_5": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_decorated_5.png",
  "dice_decorated_6": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_decorated_6.png",
  "dice_decorated_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_decorated_empty.png",
  "dice_decorated_question": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_decorated_question.png",
  "dice_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_empty.png",
  "dice_question": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_question.png",
  "dice_small_1": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_small_1.png",
  "dice_small_2": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_small_2.png",
  "dice_small_3": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_small_3.png",
  "dice_small_4": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_small_4.png",
  "dice_small_5": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_small_5.png",
  "dice_small_6": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_small_6.png",
  "dice_small_empty": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_small_empty.png",
  "dice_small_question": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/dice_small_question.png",
  "other_suit_clubs": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/other_suit_clubs.png",
  "other_suit_diamonds": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/other_suit_diamonds.png",
  "other_suit_hearts": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/other_suit_hearts.png",
  "other_suit_spades": "/assets/kenney_playing-cards-pack/PNG/Cards (small)/other_suit_spades.png",
};

// CARDS_TILESHEET (6 files)
export const cardsTilesheet = {
  "cardsLarge_tilemap_packed": "/assets/kenney_playing-cards-pack/Tilesheet/cardsLarge_tilemap_packed.png",
  "cardsLarge_tilemap": "/assets/kenney_playing-cards-pack/Tilesheet/cardsLarge_tilemap.png",
  "cardsMedium_tilemap_packed": "/assets/kenney_playing-cards-pack/Tilesheet/cardsMedium_tilemap_packed.png",
  "cardsMedium_tilemap": "/assets/kenney_playing-cards-pack/Tilesheet/cardsMedium_tilemap.png",
  "cardsSmall_tilemap_packed": "/assets/kenney_playing-cards-pack/Tilesheet/cardsSmall_tilemap_packed.png",
  "cardsSmall_tilemap": "/assets/kenney_playing-cards-pack/Tilesheet/cardsSmall_tilemap.png",
};

// UI_TILES_LARGE_THICK (91 files)
export const uiTilesLargeThick = {
  "tile_0000": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0000.png",
  "tile_0001": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0001.png",
  "tile_0002": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0002.png",
  "tile_0003": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0003.png",
  "tile_0004": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0004.png",
  "tile_0005": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0005.png",
  "tile_0006": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0006.png",
  "tile_0007": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0007.png",
  "tile_0008": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0008.png",
  "tile_0009": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0009.png",
  "tile_0010": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0010.png",
  "tile_0011": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0011.png",
  "tile_0012": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0012.png",
  "tile_0013": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0013.png",
  "tile_0014": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0014.png",
  "tile_0015": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0015.png",
  "tile_0016": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0016.png",
  "tile_0017": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0017.png",
  "tile_0018": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0018.png",
  "tile_0019": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0019.png",
  "tile_0020": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0020.png",
  "tile_0021": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0021.png",
  "tile_0022": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0022.png",
  "tile_0023": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0023.png",
  "tile_0024": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0024.png",
  "tile_0025": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0025.png",
  "tile_0026": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0026.png",
  "tile_0027": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0027.png",
  "tile_0028": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0028.png",
  "tile_0029": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0029.png",
  "tile_0030": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0030.png",
  "tile_0031": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0031.png",
  "tile_0032": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0032.png",
  "tile_0033": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0033.png",
  "tile_0034": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0034.png",
  "tile_0035": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0035.png",
  "tile_0036": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0036.png",
  "tile_0037": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0037.png",
  "tile_0038": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0038.png",
  "tile_0039": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0039.png",
  "tile_0040": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0040.png",
  "tile_0041": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0041.png",
  "tile_0042": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0042.png",
  "tile_0043": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0043.png",
  "tile_0044": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0044.png",
  "tile_0045": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0045.png",
  "tile_0046": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0046.png",
  "tile_0047": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0047.png",
  "tile_0048": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0048.png",
  "tile_0049": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0049.png",
  "tile_0050": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0050.png",
  "tile_0051": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0051.png",
  "tile_0052": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0052.png",
  "tile_0053": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0053.png",
  "tile_0054": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0054.png",
  "tile_0055": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0055.png",
  "tile_0056": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0056.png",
  "tile_0057": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0057.png",
  "tile_0058": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0058.png",
  "tile_0059": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0059.png",
  "tile_0060": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0060.png",
  "tile_0061": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0061.png",
  "tile_0062": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0062.png",
  "tile_0063": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0063.png",
  "tile_0064": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0064.png",
  "tile_0065": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0065.png",
  "tile_0066": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0066.png",
  "tile_0067": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0067.png",
  "tile_0068": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0068.png",
  "tile_0069": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0069.png",
  "tile_0070": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0070.png",
  "tile_0071": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0071.png",
  "tile_0072": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0072.png",
  "tile_0073": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0073.png",
  "tile_0074": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0074.png",
  "tile_0075": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0075.png",
  "tile_0076": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0076.png",
  "tile_0077": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0077.png",
  "tile_0078": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0078.png",
  "tile_0079": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0079.png",
  "tile_0080": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0080.png",
  "tile_0081": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0081.png",
  "tile_0082": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0082.png",
  "tile_0083": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0083.png",
  "tile_0084": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0084.png",
  "tile_0085": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0085.png",
  "tile_0086": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0086.png",
  "tile_0087": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0087.png",
  "tile_0088": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0088.png",
  "tile_0089": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0089.png",
  "tile_0090": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thick outline/tile_0090.png",
};

// UI_TILES_LARGE_THIN (91 files)
export const uiTilesLargeThin = {
  "tile_0000": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0000.png",
  "tile_0001": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0001.png",
  "tile_0002": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0002.png",
  "tile_0003": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0003.png",
  "tile_0004": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0004.png",
  "tile_0005": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0005.png",
  "tile_0006": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0006.png",
  "tile_0007": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0007.png",
  "tile_0008": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0008.png",
  "tile_0009": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0009.png",
  "tile_0010": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0010.png",
  "tile_0011": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0011.png",
  "tile_0012": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0012.png",
  "tile_0013": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0013.png",
  "tile_0014": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0014.png",
  "tile_0015": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0015.png",
  "tile_0016": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0016.png",
  "tile_0017": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0017.png",
  "tile_0018": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0018.png",
  "tile_0019": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0019.png",
  "tile_0020": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0020.png",
  "tile_0021": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0021.png",
  "tile_0022": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0022.png",
  "tile_0023": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0023.png",
  "tile_0024": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0024.png",
  "tile_0025": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0025.png",
  "tile_0026": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0026.png",
  "tile_0027": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0027.png",
  "tile_0028": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0028.png",
  "tile_0029": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0029.png",
  "tile_0030": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0030.png",
  "tile_0031": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0031.png",
  "tile_0032": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0032.png",
  "tile_0033": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0033.png",
  "tile_0034": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0034.png",
  "tile_0035": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0035.png",
  "tile_0036": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0036.png",
  "tile_0037": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0037.png",
  "tile_0038": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0038.png",
  "tile_0039": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0039.png",
  "tile_0040": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0040.png",
  "tile_0041": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0041.png",
  "tile_0042": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0042.png",
  "tile_0043": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0043.png",
  "tile_0044": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0044.png",
  "tile_0045": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0045.png",
  "tile_0046": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0046.png",
  "tile_0047": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0047.png",
  "tile_0048": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0048.png",
  "tile_0049": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0049.png",
  "tile_0050": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0050.png",
  "tile_0051": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0051.png",
  "tile_0052": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0052.png",
  "tile_0053": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0053.png",
  "tile_0054": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0054.png",
  "tile_0055": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0055.png",
  "tile_0056": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0056.png",
  "tile_0057": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0057.png",
  "tile_0058": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0058.png",
  "tile_0059": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0059.png",
  "tile_0060": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0060.png",
  "tile_0061": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0061.png",
  "tile_0062": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0062.png",
  "tile_0063": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0063.png",
  "tile_0064": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0064.png",
  "tile_0065": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0065.png",
  "tile_0066": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0066.png",
  "tile_0067": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0067.png",
  "tile_0068": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0068.png",
  "tile_0069": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0069.png",
  "tile_0070": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0070.png",
  "tile_0071": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0071.png",
  "tile_0072": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0072.png",
  "tile_0073": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0073.png",
  "tile_0074": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0074.png",
  "tile_0075": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0075.png",
  "tile_0076": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0076.png",
  "tile_0077": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0077.png",
  "tile_0078": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0078.png",
  "tile_0079": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0079.png",
  "tile_0080": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0080.png",
  "tile_0081": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0081.png",
  "tile_0082": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0082.png",
  "tile_0083": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0083.png",
  "tile_0084": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0084.png",
  "tile_0085": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0085.png",
  "tile_0086": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0086.png",
  "tile_0087": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0087.png",
  "tile_0088": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0088.png",
  "tile_0089": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0089.png",
  "tile_0090": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Large tiles/Thin outline/tile_0090.png",
};

// UI_TILES_SMALL_THICK (161 files)
export const uiTilesSmallThick = {
  "tile_0000": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0000.png",
  "tile_0001": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0001.png",
  "tile_0002": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0002.png",
  "tile_0003": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0003.png",
  "tile_0004": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0004.png",
  "tile_0005": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0005.png",
  "tile_0006": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0006.png",
  "tile_0007": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0007.png",
  "tile_0008": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0008.png",
  "tile_0009": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0009.png",
  "tile_0010": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0010.png",
  "tile_0011": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0011.png",
  "tile_0012": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0012.png",
  "tile_0013": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0013.png",
  "tile_0014": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0014.png",
  "tile_0015": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0015.png",
  "tile_0016": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0016.png",
  "tile_0017": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0017.png",
  "tile_0018": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0018.png",
  "tile_0019": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0019.png",
  "tile_0020": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0020.png",
  "tile_0021": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0021.png",
  "tile_0022": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0022.png",
  "tile_0023": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0023.png",
  "tile_0024": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0024.png",
  "tile_0025": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0025.png",
  "tile_0026": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0026.png",
  "tile_0027": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0027.png",
  "tile_0028": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0028.png",
  "tile_0029": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0029.png",
  "tile_0030": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0030.png",
  "tile_0031": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0031.png",
  "tile_0032": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0032.png",
  "tile_0033": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0033.png",
  "tile_0034": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0034.png",
  "tile_0035": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0035.png",
  "tile_0036": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0036.png",
  "tile_0037": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0037.png",
  "tile_0038": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0038.png",
  "tile_0039": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0039.png",
  "tile_0040": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0040.png",
  "tile_0041": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0041.png",
  "tile_0042": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0042.png",
  "tile_0043": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0043.png",
  "tile_0044": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0044.png",
  "tile_0045": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0045.png",
  "tile_0046": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0046.png",
  "tile_0047": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0047.png",
  "tile_0048": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0048.png",
  "tile_0049": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0049.png",
  "tile_0050": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0050.png",
  "tile_0051": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0051.png",
  "tile_0052": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0052.png",
  "tile_0053": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0053.png",
  "tile_0054": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0054.png",
  "tile_0055": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0055.png",
  "tile_0056": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0056.png",
  "tile_0057": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0057.png",
  "tile_0058": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0058.png",
  "tile_0059": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0059.png",
  "tile_0060": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0060.png",
  "tile_0061": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0061.png",
  "tile_0062": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0062.png",
  "tile_0063": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0063.png",
  "tile_0064": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0064.png",
  "tile_0065": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0065.png",
  "tile_0066": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0066.png",
  "tile_0067": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0067.png",
  "tile_0068": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0068.png",
  "tile_0069": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0069.png",
  "tile_0070": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0070.png",
  "tile_0071": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0071.png",
  "tile_0072": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0072.png",
  "tile_0073": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0073.png",
  "tile_0074": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0074.png",
  "tile_0075": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0075.png",
  "tile_0076": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0076.png",
  "tile_0077": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0077.png",
  "tile_0078": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0078.png",
  "tile_0079": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0079.png",
  "tile_0080": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0080.png",
  "tile_0081": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0081.png",
  "tile_0082": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0082.png",
  "tile_0083": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0083.png",
  "tile_0084": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0084.png",
  "tile_0085": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0085.png",
  "tile_0086": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0086.png",
  "tile_0087": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0087.png",
  "tile_0088": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0088.png",
  "tile_0089": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0089.png",
  "tile_0090": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0090.png",
  "tile_0091": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0091.png",
  "tile_0092": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0092.png",
  "tile_0093": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0093.png",
  "tile_0094": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0094.png",
  "tile_0095": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0095.png",
  "tile_0096": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0096.png",
  "tile_0097": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0097.png",
  "tile_0098": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0098.png",
  "tile_0099": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0099.png",
  "tile_0100": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0100.png",
  "tile_0101": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0101.png",
  "tile_0102": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0102.png",
  "tile_0103": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0103.png",
  "tile_0104": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0104.png",
  "tile_0105": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0105.png",
  "tile_0106": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0106.png",
  "tile_0107": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0107.png",
  "tile_0108": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0108.png",
  "tile_0109": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0109.png",
  "tile_0110": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0110.png",
  "tile_0111": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0111.png",
  "tile_0112": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0112.png",
  "tile_0113": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0113.png",
  "tile_0114": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0114.png",
  "tile_0115": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0115.png",
  "tile_0116": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0116.png",
  "tile_0117": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0117.png",
  "tile_0118": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0118.png",
  "tile_0119": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0119.png",
  "tile_0120": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0120.png",
  "tile_0121": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0121.png",
  "tile_0122": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0122.png",
  "tile_0123": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0123.png",
  "tile_0124": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0124.png",
  "tile_0125": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0125.png",
  "tile_0126": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0126.png",
  "tile_0127": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0127.png",
  "tile_0128": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0128.png",
  "tile_0129": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0129.png",
  "tile_0130": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0130.png",
  "tile_0131": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0131.png",
  "tile_0132": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0132.png",
  "tile_0133": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0133.png",
  "tile_0134": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0134.png",
  "tile_0135": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0135.png",
  "tile_0136": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0136.png",
  "tile_0137": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0137.png",
  "tile_0138": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0138.png",
  "tile_0139": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0139.png",
  "tile_0140": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0140.png",
  "tile_0141": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0141.png",
  "tile_0142": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0142.png",
  "tile_0143": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0143.png",
  "tile_0144": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0144.png",
  "tile_0145": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0145.png",
  "tile_0146": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0146.png",
  "tile_0147": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0147.png",
  "tile_0148": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0148.png",
  "tile_0149": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0149.png",
  "tile_0150": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0150.png",
  "tile_0151": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0151.png",
  "tile_0152": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0152.png",
  "tile_0153": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0153.png",
  "tile_0154": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0154.png",
  "tile_0155": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0155.png",
  "tile_0156": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0156.png",
  "tile_0157": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0157.png",
  "tile_0158": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0158.png",
  "tile_0159": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0159.png",
  "tile_0160": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thick outline/tile_0160.png",
};

// UI_TILES_SMALL_THIN (161 files)
export const uiTilesSmallThin = {
  "tile_0000": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0000.png",
  "tile_0001": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0001.png",
  "tile_0002": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0002.png",
  "tile_0003": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0003.png",
  "tile_0004": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0004.png",
  "tile_0005": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0005.png",
  "tile_0006": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0006.png",
  "tile_0007": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0007.png",
  "tile_0008": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0008.png",
  "tile_0009": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0009.png",
  "tile_0010": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0010.png",
  "tile_0011": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0011.png",
  "tile_0012": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0012.png",
  "tile_0013": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0013.png",
  "tile_0014": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0014.png",
  "tile_0015": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0015.png",
  "tile_0016": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0016.png",
  "tile_0017": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0017.png",
  "tile_0018": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0018.png",
  "tile_0019": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0019.png",
  "tile_0020": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0020.png",
  "tile_0021": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0021.png",
  "tile_0022": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0022.png",
  "tile_0023": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0023.png",
  "tile_0024": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0024.png",
  "tile_0025": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0025.png",
  "tile_0026": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0026.png",
  "tile_0027": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0027.png",
  "tile_0028": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0028.png",
  "tile_0029": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0029.png",
  "tile_0030": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0030.png",
  "tile_0031": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0031.png",
  "tile_0032": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0032.png",
  "tile_0033": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0033.png",
  "tile_0034": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0034.png",
  "tile_0035": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0035.png",
  "tile_0036": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0036.png",
  "tile_0037": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0037.png",
  "tile_0038": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0038.png",
  "tile_0039": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0039.png",
  "tile_0040": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0040.png",
  "tile_0041": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0041.png",
  "tile_0042": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0042.png",
  "tile_0043": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0043.png",
  "tile_0044": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0044.png",
  "tile_0045": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0045.png",
  "tile_0046": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0046.png",
  "tile_0047": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0047.png",
  "tile_0048": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0048.png",
  "tile_0049": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0049.png",
  "tile_0050": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0050.png",
  "tile_0051": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0051.png",
  "tile_0052": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0052.png",
  "tile_0053": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0053.png",
  "tile_0054": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0054.png",
  "tile_0055": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0055.png",
  "tile_0056": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0056.png",
  "tile_0057": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0057.png",
  "tile_0058": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0058.png",
  "tile_0059": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0059.png",
  "tile_0060": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0060.png",
  "tile_0061": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0061.png",
  "tile_0062": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0062.png",
  "tile_0063": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0063.png",
  "tile_0064": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0064.png",
  "tile_0065": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0065.png",
  "tile_0066": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0066.png",
  "tile_0067": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0067.png",
  "tile_0068": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0068.png",
  "tile_0069": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0069.png",
  "tile_0070": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0070.png",
  "tile_0071": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0071.png",
  "tile_0072": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0072.png",
  "tile_0073": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0073.png",
  "tile_0074": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0074.png",
  "tile_0075": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0075.png",
  "tile_0076": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0076.png",
  "tile_0077": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0077.png",
  "tile_0078": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0078.png",
  "tile_0079": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0079.png",
  "tile_0080": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0080.png",
  "tile_0081": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0081.png",
  "tile_0082": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0082.png",
  "tile_0083": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0083.png",
  "tile_0084": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0084.png",
  "tile_0085": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0085.png",
  "tile_0086": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0086.png",
  "tile_0087": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0087.png",
  "tile_0088": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0088.png",
  "tile_0089": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0089.png",
  "tile_0090": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0090.png",
  "tile_0091": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0091.png",
  "tile_0092": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0092.png",
  "tile_0093": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0093.png",
  "tile_0094": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0094.png",
  "tile_0095": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0095.png",
  "tile_0096": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0096.png",
  "tile_0097": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0097.png",
  "tile_0098": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0098.png",
  "tile_0099": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0099.png",
  "tile_0100": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0100.png",
  "tile_0101": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0101.png",
  "tile_0102": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0102.png",
  "tile_0103": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0103.png",
  "tile_0104": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0104.png",
  "tile_0105": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0105.png",
  "tile_0106": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0106.png",
  "tile_0107": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0107.png",
  "tile_0108": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0108.png",
  "tile_0109": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0109.png",
  "tile_0110": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0110.png",
  "tile_0111": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0111.png",
  "tile_0112": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0112.png",
  "tile_0113": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0113.png",
  "tile_0114": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0114.png",
  "tile_0115": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0115.png",
  "tile_0116": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0116.png",
  "tile_0117": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0117.png",
  "tile_0118": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0118.png",
  "tile_0119": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0119.png",
  "tile_0120": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0120.png",
  "tile_0121": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0121.png",
  "tile_0122": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0122.png",
  "tile_0123": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0123.png",
  "tile_0124": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0124.png",
  "tile_0125": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0125.png",
  "tile_0126": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0126.png",
  "tile_0127": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0127.png",
  "tile_0128": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0128.png",
  "tile_0129": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0129.png",
  "tile_0130": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0130.png",
  "tile_0131": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0131.png",
  "tile_0132": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0132.png",
  "tile_0133": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0133.png",
  "tile_0134": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0134.png",
  "tile_0135": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0135.png",
  "tile_0136": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0136.png",
  "tile_0137": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0137.png",
  "tile_0138": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0138.png",
  "tile_0139": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0139.png",
  "tile_0140": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0140.png",
  "tile_0141": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0141.png",
  "tile_0142": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0142.png",
  "tile_0143": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0143.png",
  "tile_0144": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0144.png",
  "tile_0145": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0145.png",
  "tile_0146": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0146.png",
  "tile_0147": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0147.png",
  "tile_0148": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0148.png",
  "tile_0149": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0149.png",
  "tile_0150": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0150.png",
  "tile_0151": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0151.png",
  "tile_0152": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0152.png",
  "tile_0153": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0153.png",
  "tile_0154": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0154.png",
  "tile_0155": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0155.png",
  "tile_0156": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0156.png",
  "tile_0157": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0157.png",
  "tile_0158": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0158.png",
  "tile_0159": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0159.png",
  "tile_0160": "/assets/kenney_ui-pack-pixel-adventure/Tiles/Small tiles/Thin outline/tile_0160.png",
};

// UI_TILESHEETS (8 files)
export const uiTilesheets = {
  "tilemap_packed": "/assets/kenney_ui-pack-pixel-adventure/Tilesheets/Large tiles/Thick outline/tilemap_packed.png",
  "tilemap": "/assets/kenney_ui-pack-pixel-adventure/Tilesheets/Large tiles/Thick outline/tilemap.png",
  "tilemap_packed": "/assets/kenney_ui-pack-pixel-adventure/Tilesheets/Large tiles/Thin outline/tilemap_packed.png",
  "tilemap": "/assets/kenney_ui-pack-pixel-adventure/Tilesheets/Large tiles/Thin outline/tilemap.png",
  "tilemap_packed": "/assets/kenney_ui-pack-pixel-adventure/Tilesheets/Small tiles/Thick outline/tilemap_packed.png",
  "tilemap": "/assets/kenney_ui-pack-pixel-adventure/Tilesheets/Small tiles/Thick outline/tilemap.png",
  "tilemap_packed": "/assets/kenney_ui-pack-pixel-adventure/Tilesheets/Small tiles/Thin outline/tilemap_packed.png",
  "tilemap": "/assets/kenney_ui-pack-pixel-adventure/Tilesheets/Small tiles/Thin outline/tilemap.png",
};

export const assets = {
  sounds,
  cardsLarge,
  cardsMedium,
  cardsSmall,
  cardsTilesheet,
  uiTilesLargeThick,
  uiTilesLargeThin,
  uiTilesSmallThick,
  uiTilesSmallThin,
  uiTilesheets,
};

export default assets;
// --- Helpers ---
// Get a playing card path by suit + rank at a given size.
// suit: 'clubs'|'diamonds'|'hearts'|'spades'; rank: '02'..'10'|'A'|'J'|'Q'|'K'
// size: 'large'|'medium'|'small' (default 'large')
export function getCard(suit, rank, size = 'large') {
  const map = { large: cardsLarge, medium: cardsMedium, small: cardsSmall }[size];
  return map[`card_${suit}_${rank}`] || null;
}

// Get a sound path by basename (e.g. 'click_001', 'error_003').
export function getSound(name) {
  return sounds[name] || null;
}
